site_name: Sample Tech Blog
docs_dir: docs/
site_url: https://techblog.github.io/
site_dir: site/
site_author: Eunjung Kim
site_description: >-
  This tech blog conveys the journey of developing a simulation platform for the future of mobility.

repo_name: techblog.github.io
repo_url: https://github.com/sample-docs/techblog.github.io
remote_branch: gh-pages
# Copyright
copyright: Copyright &copy; 2025 <a href="https://github.com/ejkim-author">ejkim-author.</a>

theme:
  name: material
  custom_dir: overrides
  logo: assets/favicon1.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate 
  favicon: 'assets/favicon1.png'
  icon:
    logo: logo

# # Plugins
# plugins:
#   - meta
#   - blog:
#       blog_dir: .
#       # blog_toc: true
#       archive: false
#   - search
#  #     separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
#   - tags:
#       tags_file: tags.md
#   #- minify:
#   #    minify_html: true
#   - rss:
#       match_path: posts/.* 
#       date_from_meta:
#         as_creation: date
#       categories:
#         - categories
#         - tags
#    - typeset

plugins:
  # - meta:
  #     meta_file: .meta.yml 
  - blog:
      blog_dir: .
      archive: false
      categories_url_format: "category/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      #categories_sort_by: !!python/name:material.plugins.blog.view_post_count
      #categories_sort_reverse: true
      # categories_allowed:
      #   - Search
      #   - Performance
      post_dir: "posts/"
      post_slugify_separator: "-"
      post_url_format: "{date}/{file}"
  - search
  - tags:
      tags_file: tags.md
  #- typeset
  # - info:
  #     archive_stop_on_violation: false

# Hooks
# hooks:
#   - overrides/hooks/translations.py

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg #!!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji #!!python/name:material.extensions.emoji.twemojii
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md

extra_css: 
  - css/extra.css
#  - css/_typeset.scss


